### ISSUE TITLE
 import pyupset as pyu

### ISSUE THREAD

**Issue by koustubhavachat** [ImSoErgodic/py-upset#13]
> Getting SyntaxError: invalid syntax on import pyupset as pyu

`Traceback (most recent call last):
  File "C:\MyWork\upset\upsetxmplgithub.py", line 1, in <module>
    import pyupset as pyu
  File "C:\Python27\lib\site-packages\pyupset\__init__.py", line 2, in <module>
    from .visualisation import plot
  File "C:\Python27\lib\site-packages\pyupset\visualisation.py", line 12
    def plot(data_dict,*, unique_keys=None, sort_by='size', inters_size_bounds=(0, np.inf),
                        ^
SyntaxError: invalid syntax`

**Comment by radlinsky** [comment]
Hello, I am seeing this same error...
![screen shot 2017-06-20 at 11 40 22 am](https://user-images.githubusercontent.com/5822595/27342156-4a039b8a-55ad-11e7-8953-542b47668e6a.png)

**Comment by samuelmiver** [comment]
Same error here:

      File "/usr/local/lib/python2.7/dist-packages/pyupset/visualisation.py", line 12
      def plot(data_dict, *, unique_keys=None, sort_by='size', inters_size_bounds=(0, np.inf),
                         ^
       SyntaxError: invalid syntax

**Comment by davidemms** [comment]
Hi

I get the same error. Is there any fix or workaround?

Thanks!
David

**Comment by popher** [comment]
Looks like it's a Python 2 issue related to having *args in the function before the remaining default arguments. 

Two solutions: 
1) Use python3.
2) Edit visualisation.py to fix this (move the * to the end of the function brackets, and check that that doesn't break anything else). 
i.e. change:
`def plot(data_dict, *, unique_keys=None, sort_by='size', inters_size_bounds=(0, np.inf),`
`         inters_degree_bounds=(1, np.inf), additional_plots=None, query=None):`
to 
`def plot(data_dict, unique_keys=None, sort_by='size', inters_size_bounds=(0, np.inf),`
`         inters_degree_bounds=(1, np.inf), additional_plots=None, query=None, *):`
I don't use python 2 so I can't test it readily.

**Comment by dhmay** [comment]
The fix above works in Python 2.7, with two changes:

1. The last argument should be "\*args", not "\*"
2. there's more than one function in visualization.py that needs to change
