### ISSUE TITLE
unsupported pickle protocol: 3 with python 2.7 

### ISSUE THREAD

**Issue by xie186** [ImSoErgodic/py-upset#23]
```
>>> from pickle import load
>>> with open('./test_data_dict.pckl', 'rb') as f:
...    data_dict = load(f)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib64/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib64/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib64/python2.7/pickle.py", line 886, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3
```
What's the possible reason for this error?  Thanks.

**Comment by unitemir** [comment]
:c
